# Generated by Django 5.0.1 on 2024-03-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('employee', 'employee'), ('admin', 'admin'), ('customer', 'customer')], default='customer', max_length=25),
        ),
    ]
